package tech.csm.controller;

import java.security.Principal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import tech.csm.entity.User;
import tech.csm.payload.UserRequest;
import tech.csm.payload.UserResponse;
import tech.csm.service.UserService;
import tech.csm.util.JwtUtil;

@RestController
@RequestMapping("/user")
public class UserController {

	@Autowired
	private UserService userService;

	@Autowired
	private AuthenticationManager authenticationManager;

	@Autowired
	private JwtUtil jwtUtil;

	@PostMapping("/save")
	public ResponseEntity<String> saveuser(@RequestBody User user) {
		User saveUser = userService.saveUser(user);
		return ResponseEntity.ok("user created with id : " + saveUser.getUserId());
	}

	@PostMapping("/login")
	public ResponseEntity<UserResponse> login(@RequestBody UserRequest userRequest) {
		authenticationManager.authenticate(
				new UsernamePasswordAuthenticationToken(userRequest.getUserName(), userRequest.getPasssword()));
		String token = jwtUtil.generateToken(userRequest.getUserName());
		return ResponseEntity.ok(new UserResponse(token, "Generated by Mr.Akshay"));
	}

	@GetMapping("/welcome")
	public ResponseEntity<String> showUserData(Principal principal) {
		System.out.println(principal.getClass().getName());
		System.out.println(principal);
		return ResponseEntity.ok("Hello: " + principal.getName());
	}

}
